### ISSUE TITLE
Option to hide "+ Add another list"

### ISSUE THREAD

**Issue by mxmilkiib** [christiankaindl/trello-super-powers#16]
I've my lists sorted, don't need to waste space with a whole column dedicated to adding a new list.

Maybe have add a "+ Add another list" link next to the "Compact Mode" link?

**Comment by christiankaindl** [comment]
I am planning on making a development sprint for Trello Super Powers in the next one or two weeks, because it needs some love.

This will definitely be in the list of new features! Placement next to the "Compact Mode" button is nice I think.

**Comment by christiankaindl** [comment]
Hey @milkmiruku, I played around a a bit with this now. Apparently, I could not manage to make it work. Trello calls some internal functions to create a new list, which I cannot access, and thus not be able to put a "Add new List" button in the toolbar.

This means I don't see a way to do this feature right now. However, it is possible to create Lists using the [Trello API](https://developers.trello.com). So I will revisit this issue when we have added Authentication support.

**Comment by BKDevelop** [comment]
Hi @christiankaindl 
I know you want to implement this feature in a different way after you add Authentication support. However, I would like to propose a different solution to clean up trello's UI - at least temporarily:

![hideAddNewList](https://user-images.githubusercontent.com/26822220/66274598-7e10d100-e880-11e9-94d4-61df8d46089e.gif)

At first I wanted to completely remove the button, since it's feature is already provided by double clicking the board. I settled on a toggle for now, since I think this would be more in line with the general approach of the plugin.

What do you think? If you like, I would love to contribute and open a PR ;)

**Comment by christiankaindl** [comment]
Hey @BKDevelop thanks for reaching out!

Yeah your are right, as a temporary solution we could add the possibility to simply hide the column (and not provide a alternative button to create a list). Feature-wise, I would suggest adding a settings-toggle in the Add-On preferences. A dedicated button in the toolbar is not necessary in my opinion.

If you can draft up and open a PR, that's awesome. Just Do It! We can then iterate on the PR together.

**Comment by BKDevelop** [comment]
Oh yes, I would also prefer not having a toggle button taking up space!
I'll open a PR as soon as possible :)

Christian Kaindl <notifications@github.com> schrieb am Mo., 7. Okt. 2019,
13:40:

**Comment by koobs** [comment]
@christiankaindl This issue can be closed. Dependent PR resolved

**Comment by christiankaindl** [comment]
Good catch, thanks!
