### ISSUE TITLE
Label names not visible

### ISSUE THREAD

**Issue by Rj7** [christiankaindl/trello-super-powers#25]
For last week or so, the label name stopped showing in the boards. But, when the card is opened, the label is visible in the detail page.

**Comment by Rj7** [comment]
My bad, not a bug. I just had to click on any of the label again. Seems like trello feature.

**Comment by christiankaindl** [comment]
Ok, glad you could resolve it 👍

Yes, Trello has said feature that when you click on a label the label text becomes visible.

But if you have enabled visible labels in the Trello Super Powers settings, then the labels should be visible no matter what (we also do custom styling so they look better).

So my question is: did you have the label feature enabled? Because then it likely is a bug.

**Comment by Rj7** [comment]
I had the feature enabled. I tried it again now. The label name disappears and re-appears when I click on them. But I think the styling is still this addon's styling.  I am on firefox 67.

**Comment by christiankaindl** [comment]
New version 0.12.2 with a fix is up soon

**Comment by christiankaindl** [comment]
Version 0.12.2 is not up! Thanks @Rj7  for bringing this to my attention :clap: 

It seems like this issue was caused by a minor CSS styling change by trello.com
