### ISSUE TITLE
add-on works once in Firefox

### ISSUE THREAD

**Issue by telethonic** [christiankaindl/trello-super-powers#34]
Thanks for making this plugin :)

This is probably related to #32 

running Firefox 93.0 on CentOS 7.9

After installing the add-on and reloading trello, the "Compact mode" button is visible and works.

Then it disappears, with the console showing:

`[Trello Super Powers] Could not initialize features. Try reloading the page, or if it keeps happening submit an issue at https://github.com/christiankaindl/trello-super-powers/issues inject.js:254:13
    initializeFeatures moz-extension://da377a86-ab8b-408e-8d43-957eab857993/inject/inject.js:254
    (Async: setTimeout handler)
    initializeFeatures moz-extension://da377a86-ab8b-408e-8d43-957eab857993/inject/inject.js:261
    (Async: setTimeout handler)
    initializeFeatures moz-extension://da377a86-ab8b-408e-8d43-957eab857993/inject/inject.js:261
    <anonymous> moz-extension://da377a86-ab8b-408e-8d43-957eab857993/inject/inject.js:365`

Another question (which may be moot once this works again): how do you resize the lists?

**Comment by christiankaindl** [comment]
Hi @telethonic thanks for reaching out :) I could not exactly reproduce the issue, but investigated the error and pushed a potential fix. **Please update to the lastest version (0.13.1) and let me know if the issue still persists!**

Regarding the resizable lists: there is currently a bug where the feature breaks due to a race condition with some trello scripts. See #23 for that

**Comment by telethonic** [comment]
Sorry for the late reply: yes, the new version fixed it, thanks :-)

**Comment by christiankaindl** [comment]
Awesome!
